### ISSUE TITLE
Build not work (locally and at Netify)

### ISSUE THREAD

**Issue by ww7** [philhawksworth/hawksworx.com#32]
Got error on `yarn run build` 
(`build": "gulp build & ELEVENTY_ENV=prod eleventy && yarn run build:lambda"`)
```
`Error` was thrown:
    Error: Request failed with status code 400
        at createError (/Users/dad/Code/node/hawksworx.com/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/Users/dad/Code/node/hawksworx.com/node_modules/axios/lib/core/settle.js:18:12)
        at IncomingMessage.handleStreamEnd (/Users/dad/Code/node/hawksworx.com/node_modules/axios/lib/adapters/http.js:202:11)
        at IncomingMessage.emit (events.js:194:15)
        at endReadableNT (_stream_readable.js:1125:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
```

But `yarn run build:lambda`, `yarn start`, `yarn dryrun` - works

**Comment by ww7** [comment]
Seems `ELEVENTY_ENV=prod` try to fetch data for `philhawksworth` from instagram/twitter and fail due private API keys or etc
`hawksworx.com` is not starter, this is not issue
